const STORAGE_KEY="bp01_fantasy_wonderland_collection_v1";
const rarityOrder=["CR","GR","SR","U","C","RR","ER","SPR","GR※","ER※","SPR※","CR※","RR※"];
let saves={};
function loadSaves(){try{saves=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}catch{saves={}}}
function saveSaves(){localStorage.setItem(STORAGE_KEY,JSON.stringify(saves))}
function getSave(code){if(!saves[code])saves[code]={owned:false,wishlist:false,qty:0,dupes:0};return saves[code]}
function setView(view){statusFilter.value=view;render()}
function uniqueRarities(){return [...new Set(BP01_CARDS.map(c=>c.rarity))].sort((a,b)=>rarityOrder.indexOf(a)-rarityOrder.indexOf(b))}
function renderOddsGuide(){oddsGrid.innerHTML=uniqueRarities().map(r=>{let odds=BP01_CARDS.find(c=>c.rarity===r)?.odds||"Odds not listed";return `<div class="odds-pill"><b>${r}</b><br>${odds}</div>`}).join("")}
function setupFilters(){rarityFilter.innerHTML=`<option value="">All Rarities</option>`+uniqueRarities().map(r=>`<option value="${r}">${r}</option>`).join("");["searchInput","rarityFilter","statusFilter"].forEach(id=>{document.getElementById(id).addEventListener("input",render);document.getElementById(id).addEventListener("change",render)});clearBtn.onclick=()=>{searchInput.value="";rarityFilter.value="";statusFilter.value="all";render()}}
function filteredCards(){let q=searchInput.value.toLowerCase().trim(),rarity=rarityFilter.value,status=statusFilter.value;return BP01_CARDS.filter(card=>{let s=getSave(card.code);if(rarity&&card.rarity!==rarity)return false;if(status==="owned"&&!s.owned)return false;if(status==="missing"&&s.owned)return false;if(status==="wishlist"&&!s.wishlist)return false;if(status==="dupes"&&Number(s.dupes||0)<=0)return false;if(q&&!`${card.code} ${card.name} ${card.rarity} ${card.odds}`.toLowerCase().includes(q))return false;return true})}
function updateStats(showing){let total=BP01_CARDS.length,owned=BP01_CARDS.filter(c=>getSave(c.code).owned).length,missing=total-owned,dupes=BP01_CARDS.reduce((sum,c)=>sum+Number(getSave(c.code).dupes||0),0),percent=total?Math.round(owned/total*100):0;statShowing.textContent=showing;statOwned.textContent=owned;statMissing.textContent=missing;statDupes.textContent=dupes;statPercent.textContent=percent+"%";progressBar.style.width=percent+"%";totalCards.textContent=total}
function esc(str){return String(str).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function cardHTML(card){let s=getSave(card.code);return `<article class="card ${s.owned?"owned":""}">${s.wishlist?`<div class="wishlist-badge">Wishlist</div>`:""}<div class="card-img" onclick="openCard('${card.code}')"><img src="${card.image}" alt="${esc(card.code+" "+card.name)}" loading="lazy"></div><div class="card-body"><div class="code">${card.code}</div><div class="name">${esc(card.name)}</div><span class="rarity">${card.rarity}</span><div class="odds">${esc(card.odds)}</div><div class="qty-row"><label>Qty<input type="number" min="0" value="${s.qty||0}" onchange="updateQty('${card.code}',this.value)"></label><label>Dupes<input type="number" min="0" value="${s.dupes||0}" onchange="updateDupes('${card.code}',this.value)"></label></div><div class="card-actions"><button onclick="toggleOwned('${card.code}')">${s.owned?"Owned ✓":"Mark Owned"}</button><button onclick="toggleWishlist('${card.code}')">${s.wishlist?"Wish ✓":"Wishlist"}</button></div></div></article>`}
function render(){let list=filteredCards();cardsGrid.innerHTML=list.map(cardHTML).join("");updateStats(list.length)}
function toggleOwned(code){let s=getSave(code);s.owned=!s.owned;if(s.owned&&Number(s.qty||0)===0)s.qty=1;saveSaves();render()}
function toggleWishlist(code){let s=getSave(code);s.wishlist=!s.wishlist;saveSaves();render()}
function updateQty(code,value){let s=getSave(code);s.qty=Math.max(0,Number(value||0));s.owned=s.qty>0;saveSaves();render()}
function updateDupes(code,value){let s=getSave(code);s.dupes=Math.max(0,Number(value||0));saveSaves();render()}
function openCard(code){let card=BP01_CARDS.find(c=>c.code===code),s=getSave(code);dialogContent.innerHTML=`<div class="modal-card"><div><img src="${card.image}" alt="${esc(card.code)}"></div><div><h2>${card.code}</h2><h3>${esc(card.name)}</h3><p><strong>Rarity:</strong> ${card.rarity}</p><p><strong>Pull Odds:</strong> ${esc(card.odds)}</p><p><strong>Owned:</strong> ${s.owned?"Yes":"No"}</p><p><strong>Quantity:</strong> ${s.qty||0}</p><p><strong>Duplicates:</strong> ${s.dupes||0}</p><p><a class="btn" href="${card.wiki}" target="_blank" rel="noopener">Open Wiki Card Page</a></p></div></div>`;cardDialog.showModal()}
function download(name,text,type){let blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function exportCsv(){let rows=[["Code","Name","Rarity","Odds","Owned","Qty","Duplicates","Wishlist","Image","Wiki"]];BP01_CARDS.forEach(card=>{let s=getSave(card.code);rows.push([card.code,card.name,card.rarity,card.odds,s.owned?"Yes":"No",s.qty||0,s.dupes||0,s.wishlist?"Yes":"No",card.image,card.wiki])});download("BP01_Fantasy_Wonderland_Checklist.csv",rows.map(row=>row.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n"),"text/csv")}
backupBtn.onclick=()=>download("BP01_Collection_Backup.json",JSON.stringify(saves,null,2),"application/json");exportCsvBtn.onclick=exportCsv;importFile.onchange=async()=>{let file=importFile.files[0];if(!file)return;saves=JSON.parse(await file.text());saveSaves();render()};closeDialog.onclick=()=>cardDialog.close();loadSaves();setupFilters();renderOddsGuide();render();